apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  labels:
    app: apache-webserver
spec:
  replicas: 2 # You can adjust the number of replicas
  selector:
    matchLabels:
      app: apache-webserver
  template:
    metadata:
      labels:
        app: apache-webserver
    spec:
      containers:
      - name: apache-container
        image: httpd:latest # Uses the latest official Apache HTTP Server image
        ports:
        - containerPort: 80 # Apache listens on port 80 by default
